var isDone = false;
var integer = 6;
var decimal = 3.14;
var color = "blue";
console.log("isDone: " + isDone);
console.log("integer: " + integer);
console.log("decimal: " + decimal);
console.log("color: " + color);
console.log("\n   isDone: " + isDone + " \n   integer: " + integer + "\n   decimal: " + decimal + "\n   color: " + color + "\n");
var list1 = [1, 2, 3];
var list2 = ['4a', '5b', '6c'];
console.log(list1);
console.log(list2);
var badList = ["a", "2", "c"];
console.log(badList);
var myObj = { a: 1, b: "Hi!" };
console.log(myObj);
var list3 = [1, true, "free"];
list3[1] = 100; // No Error
console.log(list3);
